model_name: fasterrcnn_resnet50_fpn
input_size: [800, 800]
layers_to_hook:
  - body.layer1
  - body.layer2
  - body.layer3
  - body.layer4
  - fpn.inner_blocks.0
  - fpn.inner_blocks.1
baseline_fps: null
baseline_map: null
