model_name: mobilenet_ssd
input_size: [320, 320]

layers_to_hook:
  - features.0
  - features.1
  - features.2
  - features.4
  - features.7
  - features.10
  - features.14

notes: "For ssdlite320_mobilenet_v3_large from torchvision"
